AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LectureClip Lambda functions (SAM template for local dev)

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    Environment:
      Variables:
        BUCKET_NAME: !Ref BucketName
        REGION: !Ref AWS::Region

Parameters:
  BucketName:
    Type: String
    Default: lectureclip-user-videos-local
    Description: S3 bucket name (use your real dev bucket for presigned URLs to work)

  StateMachineArn:
    Type: String
    Default: ""
    Description: Step Functions audio-transcription state machine ARN

  TranscribeTable:
    Type: String
    Default: lectureclip-transcriptions-local
    Description: DynamoDB table name for transcription job tracking

Resources:
  VideoUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureclip-video-upload
      Handler: index.handler
      CodeUri: src/lambdas/video-upload/

  MultipartInitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureclip-multipart-init
      Handler: index.handler
      CodeUri: src/lambdas/multipart-init/

  MultipartCompleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureclip-multipart-complete
      Handler: index.handler
      CodeUri: src/lambdas/multipart-complete/

  S3TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureclip-s3-trigger
      Handler: index.handler
      CodeUri: src/lambdas/s3-trigger/
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref StateMachineArn

  StartTranscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureclip-start-transcribe
      Handler: index.handler
      CodeUri: src/lambdas/start-transcribe/
      Timeout: 60
      Environment:
        Variables:
          TRANSCRIBE_TABLE: !Ref TranscribeTable
          TRANSCRIPTS_BUCKET: !Ref BucketName

  ProcessTranscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lectureclip-process-transcribe
      Handler: index.handler
      CodeUri: src/lambdas/process-transcribe/
      Timeout: 60
      Environment:
        Variables:
          TRANSCRIBE_TABLE: !Ref TranscribeTable
